[build-system]
requires = [
    'nvidia-ml-py',
    'numpy',
    'torch>=1.7.0',
    'pillow',
    'opencv-python',
    'ruamel.yaml',
    'setuptools',
    'wheel',
]
build-backend = 'setuptools.build_meta'
